name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - name: Build Flutter Web
        run: |
          echo "GOOGLE_API_KEY=${{secrets.GOOGLE_API_KEY}}" > .env
          echo "API_BASE_URL=${{secrets.API_BASE_URL}}" >> .env
          flutter build web

      - name: Test SSH connection
        env:
          key: ${{secrets.EC2_SSH_KEY}}
          host: ${{secrets.EC2_HOST}}
          username: ${{secrets.EC2_USER}}

        run: |
          echo "$key" > private_key && chmod 600 private_key
          echo "Testing SSH connection with host:$host user:$username"
          ssh -o StrictHostKeyChecking=no -i private_key ${username}@${host}

      - name: Compress build files
        run: tar -czf build.tar.gz -C build/web .

      - name: Remove files on server
        uses: appleboy/ssh-action@master
        with:
          key: ${{secrets.EC2_SSH_KEY}}
          host: ${{secrets.EC2_HOST}}
          username: ${{secrets.EC2_USER}}
          script: |
            rm -rf /var/www/frontend/*

      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          key: ${{secrets.EC2_SSH_KEY}}
          host: ${{secrets.EC2_HOST}}
          username: ${{secrets.EC2_USER}}
          source: "build.tar.gz"
          target: "/var/www/frontend"

      - name: Extract files on server
        uses: appleboy/ssh-action@master
        with:
          key: ${{secrets.EC2_SSH_KEY}}
          host: ${{secrets.EC2_HOST}}
          username: ${{secrets.EC2_USER}}
          script: |
            tar -xzf /var/www/frontend/build.tar.gz -C /var/www/frontend
            rm /var/www/frontend/build.tar.gz

      - name: Create .env on server
        uses: appleboy/ssh-action@master
        with:
          key: ${{secrets.EC2_SSH_KEY}}
          host: ${{secrets.EC2_HOST}}
          username: ${{secrets.EC2_USER}}
          script: |
            cat > /var/www/frontend/.env <<EOF
            GOOGLE_MAPS_API_KEY=${{secrets.GOOGLE_API_KEY}}
            API_BASE_URL=${{secrets.API_BASE_URL}}
            EOF
            chmod 600 /var/www/frontend/.env
